/**
 * Default set expansion cards (set: genesis).
 * 30 cards — 5 per faction.
 */
export const DEFAULT_SET_EXPANSION_CARDS = [
  // ── BITCOIN (5) ─────────────────────────────────────────────────────────────
  {
    id: "bitcoin_satoshis_disciple",
    name: "Satoshi's Disciple",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    tribe: "Token",
    cost: 2,
    attack: 3,
    health: 2,
    text: "(No effect — vanilla)",
    flavorText: "Doesn't know who Satoshi is. Doesn't need to.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_hash_rate",
    name: "Hash Rate",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    cost: 3,
    attack: 3,
    health: 3,
    text: "(No effect — vanilla)",
    flavorText: "Numbers go up.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_block_reward",
    name: "Block Reward",
    set: "genesis",
    type: "spell",
    faction: "bitcoin",
    rarity: "common",
    cost: 2,
    text: "Add two 1/1 Tokens to your hand.",
    flavorText: "Mined fresh. Still warm.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "add_to_hand", params: { card_id: "token_1_1" } },
      { trigger: "on_play", target: "hero_friendly", action: "add_to_hand", params: { card_id: "token_1_1" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_immutable_ledger",
    name: "Immutable Ledger",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "rare",
    tribe: "Protocol",
    cost: 4,
    attack: 3,
    health: 6,
    text: "HODL. Your other minions cannot have their stats reduced by card effects.",
    flavorText: "What's written stays written.",
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      { trigger: "passive", target: "all_minions_friendly", action: "immune_to", params: { effect_tag: "stat_reduction" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_the_genesis_block",
    name: "The Genesis Block",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "epic",
    cost: 6,
    attack: 5,
    health: 6,
    text: "Pump: Add a copy of every Token minion in your burn pile to your hand.",
    flavorText: "It all started here.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "return_to_hand",
        params: { from: "burn_pile", filter: "type:minion,tribe:Token", count: 99, copy: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── ETHEREUM (5) ────────────────────────────────────────────────────────────
  {
    id: "ethereum_smart_contract",
    name: "Smart Contract",
    set: "genesis",
    type: "minion",
    faction: "ethereum",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 3,
    text: "(No effect — vanilla)",
    flavorText: "Self-executing. Self-sufficient. Self-important.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "ethereum_layer_2",
    name: "Layer 2",
    set: "genesis",
    type: "minion",
    faction: "ethereum",
    rarity: "common",
    tribe: "Protocol",
    cost: 3,
    attack: 4,
    health: 2,
    text: "Ape In.",
    flavorText: "Faster. Cheaper. Still Ethereum underneath.",
    keywordsJson: [{ id: "charge", display: "Ape In" }],
    effectsJson: [{ trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "charge" } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "ethereum_gas_refund",
    name: "Gas Refund",
    set: "genesis",
    type: "spell",
    faction: "ethereum",
    rarity: "common",
    cost: 1,
    text: "Reduce the cost of a card in your hand by (2) this turn.",
    flavorText: "Rare. Cherish it.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "chosen_card_in_hand_friendly",
        action: "modify_cost",
        params: { amount: -2, duration: "this_turn" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "ethereum_mev_bot",
    name: "MEV Bot",
    set: "genesis",
    type: "minion",
    faction: "ethereum",
    rarity: "rare",
    tribe: "Protocol",
    cost: 3,
    attack: 2,
    health: 4,
    text: "Whenever your opponent plays a spell, deal 1 damage to their Hero.",
    flavorText: "Front-running since block 1.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_opponent_spell",
        target: "hero_enemy",
        action: "deal_damage",
        params: { amount: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "ethereum_the_merge",
    name: "The Merge",
    set: "genesis",
    type: "spell",
    faction: "ethereum",
    rarity: "epic",
    cost: 5,
    text: "Transform all minions on the board into 2/2 copies of themselves. They lose all keywords.",
    flavorText: "Everything changed. Nothing changed.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "all_minions",
        action: "transform",
        params: { attack: 2, health: 2, strip_keywords: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── SOLANA (5) ────────────────────────────────────────────────────────────
  {
    id: "solana_validator_node",
    name: "Validator Node",
    set: "genesis",
    type: "minion",
    faction: "solana",
    rarity: "common",
    cost: 1,
    attack: 2,
    health: 1,
    text: "(No effect — vanilla)",
    flavorText: "Online. For now.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "solana_speed_run",
    name: "Speed Run",
    set: "genesis",
    type: "minion",
    faction: "solana",
    rarity: "common",
    tribe: "Degen",
    cost: 2,
    attack: 3,
    health: 1,
    text: "Ape In.",
    flavorText: "First in. First out. Usually.",
    keywordsJson: [{ id: "charge", display: "Ape In" }],
    effectsJson: [{ trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "charge" } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "solana_tps_surge",
    name: "TPS Surge",
    set: "genesis",
    type: "spell",
    faction: "solana",
    rarity: "common",
    cost: 2,
    text: "Give all friendly minions +1 Attack and Ape In this turn.",
    flavorText: "400,000 transactions per second. On a good day.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions_friendly", action: "buff_attack", params: { amount: 1, duration: "this_turn" } },
      { trigger: "on_play", target: "all_minions_friendly", action: "give_keyword", params: { keyword: "charge" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "solana_jito_restaker",
    name: "Jito Restaker",
    set: "genesis",
    type: "minion",
    faction: "solana",
    rarity: "rare",
    tribe: "Protocol",
    cost: 3,
    attack: 3,
    health: 3,
    text: "At the start of your turn, give a random friendly minion +1 Attack.",
    flavorText: "Restaked and ready.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "start_of_turn",
        target: "random_minion_friendly",
        action: "buff_attack",
        params: { amount: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "solana_network_outage",
    name: "Network Outage",
    set: "genesis",
    type: "spell",
    faction: "solana",
    rarity: "epic",
    cost: 4,
    text: "Freeze all enemy minions for 2 turns. Draw a card.",
    flavorText: "Scheduled maintenance. Unscheduled, technically.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions_enemy", action: "freeze", params: { duration: 2 } },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── MEME (5) ──────────────────────────────────────────────────────────────
  {
    id: "meme_pepe_maxi",
    name: "Pepe Maxi",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 2,
    text: "(No effect — vanilla)",
    flavorText: "Rare. Very rare. Trust me.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_shiba_squad",
    name: "Shiba Squad",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "common",
    tribe: "Degen",
    cost: 2,
    attack: 2,
    health: 2,
    text: "(No effect — vanilla)",
    flavorText: "1 SHIB = 1 SHIB.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_rug_radar",
    name: "Rug Radar",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "common",
    cost: 1,
    text: "Look at your opponent's hand. Add a copy of one card you see to your hand.",
    flavorText: "Always check the contract.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "copy_to_hand",
        params: { from: "opponent_hand", reveal: true, pick: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_chaos_protocol",
    name: "Chaos Protocol",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "rare",
    cost: 3,
    text: "Shuffle all minions on the board. Randomly redistribute them between both sides.",
    flavorText: "Nobody knows where anything is. Beautiful.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions", action: "redistribute_board", params: { random: true } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "meme_wojak_eternal_degen",
    name: "Wojak, The Eternal Degen",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "epic",
    tribe: "KOL",
    cost: 5,
    attack: 4,
    health: 5,
    text: "Whenever this minion takes damage and survives, draw a card.",
    flavorText: "It's fine. I'm fine. Everything is fine.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_take_damage",
        target: "self",
        action: "draw_cards",
        params: { count: 1, condition: "survives" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── STABLE (5) ──────────────────────────────────────────────────────────────
  {
    id: "stable_audit_report",
    name: "Audit Report",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "common",
    cost: 1,
    text: "Draw a card.",
    flavorText: "Nothing suspicious found. Probably.",
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_treasury_reserve",
    name: "Treasury Reserve",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 3,
    text: "(No effect — vanilla)",
    flavorText: "Fully backed. Pinky promise.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_circuit_breaker",
    name: "Circuit Breaker",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "common",
    cost: 2,
    text: "Prevent all damage to your Hero this turn.",
    flavorText: "Markets halted. Resume panic tomorrow.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "immune_to", params: { effect_tag: "damage", duration: "this_turn" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_algo_stable",
    name: "Algo Stable",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    cost: 3,
    attack: 3,
    health: 3,
    text: "At the end of your turn, if your Hero has more HP than your opponent's Hero, gain 2 Armor.",
    flavorText: "Algorithmically stable. Until it isn't.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "end_of_turn",
        target: "hero_friendly",
        action: "give_armor",
        params: { amount: 2, condition: "hero_hp_leading" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_black_swan",
    name: "Black Swan",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "epic",
    cost: 6,
    text: "Destroy all minions with 4 or more Attack. Draw a card for each.",
    flavorText: "Impossible. Until it happened.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions", action: "destroy", params: { filter: "attack_gte:4" } },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count_per_destroyed: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── DEGEN (5) ─────────────────────────────────────────────────────────────
  {
    id: "degen_floor_trader",
    name: "Floor Trader",
    set: "genesis",
    type: "minion",
    faction: "degen",
    rarity: "common",
    cost: 1,
    attack: 2,
    health: 1,
    text: "(No effect — vanilla)",
    flavorText: "Buying the floor. It keeps going lower.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "degen_leverage_king",
    name: "Leverage King",
    set: "genesis",
    type: "minion",
    faction: "degen",
    rarity: "common",
    tribe: "Degen",
    cost: 3,
    attack: 5,
    health: 2,
    text: "(No effect — vanilla)",
    flavorText: "100x long. No stop loss.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "degen_fomo_buy",
    name: "FOMO Buy",
    set: "genesis",
    type: "spell",
    faction: "degen",
    rarity: "common",
    cost: 1,
    text: "Give a friendly minion +3 Attack this turn. At the end of the turn, it loses 2 Health.",
    flavorText: "Had to get in. Had to.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "buff_attack", params: { amount: 3, duration: "this_turn" } },
      { trigger: "end_of_turn", target: "chosen_minion", action: "deal_damage", params: { amount: 2, target: "self" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "degen_liquidated",
    name: "Liquidated",
    set: "genesis",
    type: "spell",
    faction: "degen",
    rarity: "rare",
    cost: 3,
    text: "Destroy a minion with 2 or less Health. Your Hero takes damage equal to its Attack.",
    flavorText: "Position closed. Hero damaged. Worth it.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "destroy", params: { filter: "health_lte:2" } },
      { trigger: "on_play", target: "hero_friendly", action: "deal_damage", params: { amount_from_target_attack: true } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "degen_degen_god",
    name: "Degen God",
    set: "genesis",
    type: "minion",
    faction: "degen",
    rarity: "epic",
    tribe: "KOL",
    cost: 7,
    attack: 6,
    health: 6,
    text: "Pump: Deal 3 damage to your Hero. Draw 3 cards.",
    flavorText: "Pain is temporary. Gains are forever. Losses are also forever.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "deal_damage", params: { amount: 3 } },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 3 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },
] as const;
