/**
 * Genesis Drop Pack exclusive cards (set: genesis_drop).
 * Only obtainable from the season / Genesis Drop pack.
 */
export const GENESIS_DROP_CARDS = [
  // ── LEGENDARIES ─────────────────────────────────────────────────────────────
  {
    id: "degen_ansem_black_bull",
    name: "Ansem, The Black Bull",
    set: "genesis_drop",
    type: "hero",
    faction: "degen",
    rarity: "legendary",
    cost: 8,
    health: 30,
    armor: 5,
    text: "Hero Power — Charge Forward (2): Give a friendly minion +2 Attack this turn. Pump: Airdrop a gold coin to each friendly minion. Each coin gives +1/+1.",
    flavorText: '"Not affiliated. Just inevitable."',
    heroPowerJson: {
      id: "hp_charge_forward",
      name: "Charge Forward",
      cost: 2,
      description: "Give a friendly minion +2 Attack this turn.",
      effect_type: "buff_attack",
      effect_params: { target: "chosen_minion_friendly", amount: 2, duration: "this_turn" },
    },
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "give_armor", params: { amount: 5 } },
      {
        trigger: "on_play",
        target: "all_minions_friendly",
        action: "buff_attack_health",
        params: { amount: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },
  {
    id: "solana_pump_fun_launchpad",
    name: "Pump.fun, The Launchpad",
    set: "genesis_drop",
    type: "location",
    faction: "solana",
    rarity: "legendary",
    tribe: "Protocol",
    cost: 5,
    durability: 3,
    text: "Tap: Summon a random 1-cost minion. It has Ape In.",
    flavorText: '"Everything starts here. Most things end here too."',
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_tap",
        target: "hero_friendly",
        action: "summon_minion",
        params: { card_id: "token_1_1", random_cost: 1, give_keyword: "charge" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },
  {
    id: "degen_the_trenches",
    name: "The Trenches",
    set: "genesis_drop",
    type: "spell",
    faction: "degen",
    rarity: "legendary",
    cost: 7,
    text: "Destroy all minions. Draw 2 cards.",
    flavorText: '"Everyone\'s fighting. Nobody knows which $ANSEM is real."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions", action: "destroy", params: {} },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },

  // ── EPICS ───────────────────────────────────────────────────────────────────
  {
    id: "degen_weekly_airdrop",
    name: "Weekly Airdrop",
    set: "genesis_drop",
    type: "spell",
    faction: "degen",
    rarity: "epic",
    cost: 4,
    text: "Give all friendly minions +1/+1. Draw 1 card.",
    flavorText: '"Creator fees redistributed. Community wins."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions_friendly", action: "buff_attack_health", params: { amount: 1 } },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },
  {
    id: "stable_whale_pod",
    name: "Whale Pod",
    set: "genesis_drop",
    type: "minion",
    faction: "stable",
    rarity: "epic",
    tribe: "Token",
    cost: 7,
    attack: 4,
    health: 7,
    text: "HODL. When another friendly minion is summoned, it gains +1/+1.",
    flavorText: '"23,000 holders and counting."',
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      {
        trigger: "passive",
        target: "all_minions_friendly",
        action: "buff_attack_health",
        params: { amount: 1, condition: "on_friendly_summon" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },
  {
    id: "degen_blknoiz06",
    name: "Blknoiz06",
    set: "genesis_drop",
    type: "minion",
    faction: "degen",
    rarity: "epic",
    tribe: "KOL",
    cost: 5,
    attack: 3,
    health: 4,
    text: "Pump: Add 2 random Legendary cards to your hand. They cost (2) less.",
    flavorText: '"@blknoiz06. The name moves markets."',
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "add_to_hand",
        params: { filter: "rarity:legendary", random: true, count: 2, cost_reduction: 2 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },

  // ── RARES ───────────────────────────────────────────────────────────────────
  {
    id: "meme_copycat_token",
    name: "Copycat Token",
    set: "genesis_drop",
    type: "minion",
    faction: "meme",
    rarity: "rare",
    tribe: "Degen",
    cost: 4,
    attack: 1,
    health: 1,
    text: "Pump: Copy the Attack and Health of the highest-cost minion on the board.",
    flavorText: '"Same name. Different contract. Good luck."',
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "self",
        action: "buff_attack_health",
        params: { copy_highest_cost_on_board: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "solana_pumpswap",
    name: "PumpSwap",
    set: "genesis_drop",
    type: "location",
    faction: "solana",
    rarity: "rare",
    tribe: "Protocol",
    cost: 3,
    durability: 3,
    text: "Tap: Swap the Attack and Health of a friendly minion.",
    flavorText: '"$19M volume in 24 hours. Just a Tuesday."',
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_tap",
        target: "chosen_minion",
        action: "buff_attack",
        params: { swap_stats: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_liquidity_pod",
    name: "Liquidity Pod",
    set: "genesis_drop",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    tribe: "Protocol",
    cost: 4,
    attack: 2,
    health: 5,
    text: "When this minion takes damage, restore half that amount (rounded down) to your Hero.",
    flavorText: '"Community-owned. Non-custodial. Unruggable. Probably."',
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_take_damage",
        target: "hero_friendly",
        action: "heal",
        params: { amount: 1, heal_ratio_of_damage: 0.5 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },

  // ── UNCOMMONS (stored as rare — no uncommon tier in schema) ────────────────
  {
    id: "meme_influencer_call",
    name: "Influencer Call",
    set: "genesis_drop",
    type: "spell",
    faction: "meme",
    rarity: "rare",
    cost: 2,
    text: "Give a minion +2 Attack this turn. If it destroys a minion, draw a card.",
    flavorText: '"One tweet. Millions moved."',
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "chosen_minion",
        action: "buff_attack",
        params: { amount: 2, duration: "this_turn" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_holder_distribution",
    name: "Holder Distribution",
    set: "genesis_drop",
    type: "spell",
    faction: "bitcoin",
    rarity: "rare",
    cost: 3,
    text: "Give all friendly minions +1/+1.",
    flavorText: '"410 million tokens. Every holder a believer."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions_friendly", action: "buff_attack_health", params: { amount: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "solana_dex_sniper",
    name: "Dex Sniper",
    set: "genesis_drop",
    type: "minion",
    faction: "solana",
    rarity: "rare",
    tribe: "Degen",
    cost: 3,
    attack: 3,
    health: 2,
    text: "Ape In. Rekt: Deal 2 damage to a random enemy.",
    flavorText: '"In before the pump. Out before you noticed."',
    keywordsJson: [
      { id: "charge", display: "Ape In" },
      { id: "deathrattle", display: "Rekt" },
    ],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "charge" } },
      { trigger: "on_death", target: "random_minion_enemy", action: "deal_damage", params: { amount: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "degen_concentration_risk",
    name: "Concentration Risk",
    set: "genesis_drop",
    type: "spell",
    faction: "degen",
    rarity: "rare",
    cost: 2,
    text: "Deal 4 damage to a minion. Your Hero takes 2 damage.",
    flavorText: '"A handful of wallets hold everything. What could go wrong."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "deal_damage", params: { amount: 4 } },
      { trigger: "on_play", target: "hero_friendly", action: "deal_damage", params: { amount: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },

  // ── COMMONS ─────────────────────────────────────────────────────────────────
  {
    id: "degen_paper_hands_panic",
    name: "Paper Hands Panic",
    set: "genesis_drop",
    type: "spell",
    faction: "degen",
    rarity: "common",
    cost: 1,
    text: "Return a friendly minion to your hand. Draw a card.",
    flavorText: '"Exit liquidity. For yourself."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "copy_to_hand", params: {} },
      { trigger: "on_play", target: "chosen_minion", action: "destroy", params: {} },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_on_chain_auditor",
    name: "On-Chain Auditor",
    set: "genesis_drop",
    type: "minion",
    faction: "stable",
    rarity: "common",
    tribe: "Protocol",
    cost: 2,
    attack: 1,
    health: 4,
    text: "HODL. Spells your opponent plays cost (1) more on the turn they are drawn.",
    flavorText: '"Rugcheck.xyz flagged it. Nobody listened."',
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      {
        trigger: "passive",
        target: "hero_enemy",
        action: "modify_cost",
        params: { target: "opponent_spells", amount: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_meme_coin_swarm",
    name: "Meme Coin Swarm",
    set: "genesis_drop",
    type: "spell",
    faction: "meme",
    rarity: "common",
    cost: 3,
    text: "Summon three 1/1 Token minions.",
    flavorText: '"First one to pump wins. The other 847 are rugs."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "summon_minion", params: { card_id: "token_1_1" } },
      { trigger: "on_play", target: "hero_friendly", action: "summon_minion", params: { card_id: "token_1_1" } },
      { trigger: "on_play", target: "hero_friendly", action: "summon_minion", params: { card_id: "token_1_1" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_bull_run_energy",
    name: "Bull Run Energy",
    set: "genesis_drop",
    type: "spell",
    faction: "bitcoin",
    rarity: "common",
    cost: 2,
    text: "Give a friendly minion +2/+2. It gains HODL until your next turn.",
    flavorText: '"33,745% in 7 days. Charge forward."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "buff_attack_health", params: { amount: 2 } },
      { trigger: "on_play", target: "chosen_minion", action: "give_keyword", params: { keyword: "taunt" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "solana_solana_validator",
    name: "Solana Validator",
    set: "genesis_drop",
    type: "minion",
    faction: "solana",
    rarity: "common",
    tribe: "Protocol",
    cost: 1,
    attack: 1,
    health: 2,
    text: "At the start of your turn, reduce the cost of the top card in your deck by (1).",
    flavorText: '"400,000 TPS. When it\'s not down."',
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "start_of_turn",
        target: "hero_friendly",
        action: "modify_cost",
        params: { target: "top_of_deck", amount: -1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "degen_thin_liquidity",
    name: "Thin Liquidity",
    set: "genesis_drop",
    type: "spell",
    faction: "degen",
    rarity: "common",
    cost: 1,
    text: "Deal 3 damage to a minion. Your Hero takes 3 damage.",
    flavorText: '"Slippage is a feature."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "deal_damage", params: { amount: 3 } },
      { trigger: "on_play", target: "hero_friendly", action: "deal_damage", params: { amount: 3 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_diamond_conviction",
    name: "Diamond Conviction",
    set: "genesis_drop",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    tribe: "Token",
    cost: 3,
    attack: 2,
    health: 5,
    text: "HODL. Cannot be returned to your hand by card effects.",
    flavorText: '"Skin in the game. All of it."',
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      { trigger: "passive", target: "self", action: "immune_to", params: { effect_tag: "return_to_hand" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
] as const;
