import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const HEROES = [
  {
    id: "hero_satoshi",
    name: "Satoshi",
    faction: "bitcoin",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_mint",
      name: "Mint",
      cost: 2,
      description: "Add a 1/1 Token to your hand.",
      effect_type: "add_to_hand",
      effect_params: { card_id: "token_1_1" },
    },
    unlockMethod: "default",
    description: "The original degen. Nobody knows who he is, which is exactly the point.",
  },
  {
    id: "hero_vitalik",
    name: "Vitalik",
    faction: "ethereum",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_gas_war",
      name: "Gas War",
      cost: 2,
      description: "The next spell you play this turn costs (1) less.",
      effect_type: "modify_cost",
      effect_params: { target: "next_spell_this_turn", amount: -1 },
    },
    unlockMethod: "default",
    description: "Invented the smart contract. Now your opponent is stuck paying extra gas.",
  },
  {
    id: "hero_toly",
    name: "Toly",
    faction: "solana",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_turbo",
      name: "Turbo",
      cost: 2,
      description: "Give a friendly minion +2 Attack this turn.",
      effect_type: "buff_attack",
      effect_params: { target: "chosen_minion_friendly", amount: 2, duration: "this_turn" },
    },
    unlockMethod: "default",
    description: "400,000 transactions per second. Except when it's 0.",
  },
  {
    id: "hero_elon",
    name: "Elon",
    faction: "meme",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_tweet",
      name: "Tweet",
      cost: 2,
      description: "Add a random Meme spell to your hand.",
      effect_type: "add_to_hand_random",
      effect_params: { filter: "type:spell,faction:meme" },
    },
    unlockMethod: "default",
    description: "One tweet moves markets. His deck is basically his Twitter feed.",
  },
  {
    id: "hero_circle_ceo",
    name: "Circle CEO",
    faction: "stable",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_yield",
      name: "Yield",
      cost: 2,
      description: "Restore 2 HP to your Hero.",
      effect_type: "heal",
      effect_params: { target: "hero_friendly", amount: 2 },
    },
    unlockMethod: "default",
    description: "Steady, stable, and incredibly boring to play against.",
  },
  {
    id: "hero_anon",
    name: "Anon",
    faction: "degen",
    hp: 30,
    armor: 0,
    heroPowerJson: {
      id: "hp_ape",
      name: "Ape",
      cost: 2,
      description: "Deal 2 damage to your own Hero. Draw a card.",
      effect_type: "multi",
      effect_params: {
        actions: [
          { type: "deal_damage", target: "hero_friendly", amount: 2 },
          { type: "draw_cards", target: "hero_friendly", amount: 1 },
        ],
      },
    },
    unlockMethod: "default",
    description: "Zero Twitter followers. Probably knows something you don't.",
  },
];

const CARDS = [
  // --- TOKENS / SPECIAL ---
  {
    id: "token_1_1",
    name: "Token",
    set: "tokens",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    tribe: "Token",
    cost: 0,
    attack: 1,
    health: 1,
    text: "",
    collectible: false,
    craftable: false,
    dustValue: 0,
    craftCost: 0,
    keywordsJson: [],
    effectsJson: [],
  },
  {
    id: "coin",
    name: "The Coin",
    set: "tokens",
    type: "spell",
    faction: "degen",
    rarity: "common",
    cost: 0,
    text: "Gain 1 Gas this turn only.",
    collectible: false,
    craftable: false,
    dustValue: 0,
    craftCost: 0,
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "deal_damage", params: { type: "temp_mana", amount: 1 } },
    ],
  },
  // --- BITCOIN CARDS ---
  {
    id: "bitcoin_paper_hands",
    name: "Paper Hands",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 2,
    text: "Rekt: Add a 1/1 Token to your hand.",
    flavorText: "Sold at the dip. Again.",
    keywordsJson: [{ id: "deathrattle", display: "Rekt" }],
    effectsJson: [
      { trigger: "on_death", target: "hero_friendly", action: "add_to_hand", params: { card_id: "token_1_1" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_baby_hodl",
    name: "Baby HODL",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 3,
    text: "HODL.",
    flavorText: "Still holding. Will never sell.",
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [{ trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_block_defender",
    name: "Block Defender",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "rare",
    cost: 3,
    attack: 2,
    health: 5,
    text: "HODL. Pump: Gain 2 Armor.",
    flavorText: "Immovable object. Unstoppable force didn't show up.",
    keywordsJson: [
      { id: "taunt", display: "HODL" },
      { id: "battlecry", display: "Pump" },
    ],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      { trigger: "on_play", target: "hero_friendly", action: "give_armor", params: { amount: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_mining_rig",
    name: "Mining Rig",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "common",
    cost: 4,
    attack: 3,
    health: 4,
    text: "At the end of your turn, add a 1/1 Token to your hand.",
    flavorText: "Loud. Expensive. Worth it.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "end_of_turn", target: "hero_friendly", action: "add_to_hand", params: { card_id: "token_1_1" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_cold_wallet",
    name: "Cold Wallet",
    set: "genesis",
    type: "weapon",
    faction: "bitcoin",
    rarity: "rare",
    tribe: "Gear",
    cost: 3,
    attack: 3,
    durability: 2,
    text: "Your Hero is immune while attacking.",
    flavorText: "Not your keys, not your coins.",
    keywordsJson: [],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_stack_sats",
    name: "Stack Sats",
    set: "genesis",
    type: "spell",
    faction: "bitcoin",
    rarity: "common",
    cost: 1,
    text: "Gain 3 Armor.",
    flavorText: "One sat at a time.",
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "hero_friendly", action: "give_armor", params: { amount: 3 } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_hodl_the_line",
    name: "Hodl the Line",
    set: "genesis",
    type: "spell",
    faction: "bitcoin",
    rarity: "common",
    cost: 2,
    text: "Give all friendly minions HODL.",
    flavorText: "We're all gonna make it.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "all_minions_friendly",
        action: "give_keyword",
        params: { keyword: "taunt" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "bitcoin_hardware_security",
    name: "Hardware Security",
    set: "genesis",
    type: "spell",
    faction: "bitcoin",
    rarity: "rare",
    cost: 3,
    text: "Give a friendly minion Moon Shot and +0/+3.",
    flavorText: "Airgapped and unbothered.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "give_divine_shield", params: {} },
      { trigger: "on_play", target: "chosen_minion", action: "buff_health", params: { amount: 3 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_maxi",
    name: "Bitcoin Maxi",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "rare",
    cost: 5,
    attack: 4,
    health: 6,
    text: "HODL. Pump: Deal 3 damage to an enemy minion.",
    flavorText: "Everything else is a scam.",
    keywordsJson: [
      { id: "taunt", display: "HODL" },
      { id: "battlecry", display: "Pump" },
    ],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      {
        trigger: "on_play",
        target: "chosen_minion",
        action: "deal_damage",
        params: { amount: 3, target_filter: "enemy" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_the_halving",
    name: "The Halving",
    set: "genesis",
    type: "spell",
    faction: "bitcoin",
    rarity: "rare",
    cost: 4,
    text: "Set an enemy minion's Attack to 1.",
    flavorText: "Supply cut. Impact doubled.",
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "chosen_minion", action: "buff_attack", params: { set_to: 1 } }],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "bitcoin_diamond_hands",
    name: "Diamond Hands",
    set: "genesis",
    type: "minion",
    faction: "bitcoin",
    rarity: "legendary",
    tribe: "Token",
    cost: 6,
    attack: 4,
    health: 9,
    text: "HODL. Cannot be destroyed by Rug Pull effects.",
    flavorText: '"I am not leaving." — posted from a phone with 2% battery',
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      { trigger: "passive", target: "self", action: "immune_to", params: { effect_tag: "destroy" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },
  {
    id: "bitcoin_hardware_ledger",
    name: "Hardware Ledger",
    set: "genesis",
    type: "weapon",
    faction: "bitcoin",
    rarity: "legendary",
    tribe: "Gear",
    cost: 4,
    attack: 4,
    durability: 2,
    text: "Rekt: Return a destroyed Secret to your hand.",
    keywordsJson: [{ id: "deathrattle", display: "Rekt" }],
    effectsJson: [
      {
        trigger: "on_death",
        target: "hero_friendly",
        action: "return_to_hand",
        params: { filter: "type:spell,keyword:secret", from: "burn_pile", count: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },
  // --- MEME CARDS ---
  {
    id: "meme_moon_boy",
    name: "Moon Boy",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 2,
    text: "Volatility 2: Stats vary ±2 when played.",
    flavorText: "Always going to the moon. Never arrives.",
    keywordsJson: [{ id: "volatility", display: "Volatility", params: { attack_variance: 2, health_variance: 2 } }],
    effectsJson: [],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_doge_gang",
    name: "Doge Gang",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "common",
    cost: 1,
    attack: 1,
    health: 1,
    text: "Pump: Add a random Meme spell to your hand.",
    flavorText: "Much wow. Very degen.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "add_to_hand",
        params: { filter: "type:spell,faction:meme", random: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_pepe_deploy",
    name: "Pepe Deploy",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "common",
    cost: 2,
    text: "Summon a 2/2 minion with Volatility 2.",
    flavorText: "Rare Pepe deployed successfully.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "summon_minion",
        params: { card_id: "meme_moon_boy", position: "random" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_hype_wave",
    name: "Hype Wave",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "common",
    cost: 1,
    text: "Give all friendly minions +1 Attack this turn.",
    flavorText: "Momentum acquired.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "all_minions_friendly",
        action: "buff_attack",
        params: { amount: 1, duration: "this_turn" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_diamond_frog",
    name: "Diamond Frog",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "rare",
    cost: 3,
    attack: 3,
    health: 3,
    text: "Pump: Flip a coin. Heads: Deal 3 damage to an enemy. Tails: Heal your Hero for 3.",
    flavorText: "Ribbit. 50/50.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "random_minion_enemy",
        action: "deal_damage",
        params: { amount: 3, condition: "coin_heads" },
      },
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "heal",
        params: { amount: 3, condition: "coin_tails" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "meme_viral_tweet",
    name: "Viral Tweet",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "rare",
    cost: 3,
    text: "Deal 2 damage to all enemies. Add a random Meme card to your hand.",
    flavorText: "Going viral in 3... 2... 1...",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "all_minions_enemy", action: "deal_damage", params: { amount: 2 } },
      { trigger: "on_play", target: "hero_enemy", action: "deal_damage", params: { amount: 2 } },
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "add_to_hand",
        params: { filter: "faction:meme", random: true },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "meme_to_the_moon",
    name: "To The Moon",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "rare",
    cost: 3,
    text: "Give a friendly minion +3/+3 and Volatility 3.",
    flavorText: "It can't go higher. Watch it go higher.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "chosen_minion",
        action: "buff_attack_health",
        params: { amount: 3, volatility: 3 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "meme_elon_shill",
    name: "Elon Shill",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "rare",
    cost: 4,
    attack: 3,
    health: 4,
    text: "Pump: All Meme minions cost (1) less this turn.",
    flavorText: "One post and the whole market moves.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "modify_cost",
        params: { filter: "type:minion,faction:meme", amount: -1, duration: "this_turn" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "meme_pump_it",
    name: "Pump It",
    set: "genesis",
    type: "spell",
    faction: "meme",
    rarity: "common",
    cost: 1,
    text: "Give a friendly minion +2 Attack.",
    flavorText: "We are so back.",
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "chosen_minion", action: "buff_attack", params: { amount: 2 } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "meme_100x_bet",
    name: "100x Bet",
    set: "genesis",
    type: "minion",
    faction: "meme",
    rarity: "rare",
    cost: 5,
    attack: 4,
    health: 4,
    text: "Volatility 4. Pump: Discover a Meme spell.",
    flavorText: "Could be 400x. Could be 0.",
    keywordsJson: [
      { id: "volatility", display: "Volatility", params: { attack_variance: 4, health_variance: 4 } },
      { id: "battlecry", display: "Pump" },
      { id: "discover", display: "Fork" },
    ],
    effectsJson: [
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "add_to_hand",
        params: { discover: true, filter: "type:spell,faction:meme" },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  // --- STABLE CARDS ---
  {
    id: "stable_risk_manager",
    name: "Risk Manager",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 3,
    text: "Pump: Draw a card.",
    flavorText: "Diversified. Hedged. Still nervous.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [{ trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_yield_farmer",
    name: "Yield Farmer",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    cost: 3,
    attack: 2,
    health: 4,
    text: "At the end of your turn, restore 1 HP to your Hero.",
    flavorText: "14% APY. On a good day.",
    keywordsJson: [],
    effectsJson: [{ trigger: "end_of_turn", target: "hero_friendly", action: "heal", params: { amount: 1 } }],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_liquidation",
    name: "Liquidation",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "common",
    cost: 2,
    text: "Destroy a minion with 3 or less Attack.",
    flavorText: "Position closed. Have a nice day.",
    keywordsJson: [],
    effectsJson: [
      {
        trigger: "on_play",
        target: "chosen_minion",
        action: "destroy",
        params: { condition: "attack_lte", value: 3 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_flash_crash",
    name: "Flash Crash",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "rare",
    cost: 4,
    text: "Deal 2 damage to all minions.",
    flavorText: "Over in milliseconds. Felt for months.",
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "all_minions", action: "deal_damage", params: { amount: 2 } }],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_collateral",
    name: "Collateral",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "common",
    cost: 1,
    text: "Draw a card. Restore 2 HP to your Hero.",
    flavorText: "Every position needs backing.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
      { trigger: "on_play", target: "hero_friendly", action: "heal", params: { amount: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_peg_defence",
    name: "Peg Defence",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    cost: 4,
    attack: 3,
    health: 6,
    text: "HODL. Whenever you heal, draw a card.",
    flavorText: "The peg will hold.",
    keywordsJson: [{ id: "taunt", display: "HODL" }],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      { trigger: "on_take_damage", target: "hero_friendly", action: "draw_cards", params: { count: 1, condition: "on_heal" } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_stablecoin",
    name: "Stablecoin",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "common",
    cost: 2,
    attack: 2,
    health: 2,
    text: "DeFi.",
    flavorText: "Not going anywhere.",
    keywordsJson: [{ id: "lifesteal", display: "DeFi" }],
    effectsJson: [{ trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "lifesteal" } }],
    collectible: true,
    craftable: true,
    dustValue: 5,
    craftCost: 40,
  },
  {
    id: "stable_dai_hard",
    name: "DAI Hard",
    set: "genesis",
    type: "spell",
    faction: "stable",
    rarity: "rare",
    cost: 3,
    text: "Silence a minion. Draw a card.",
    flavorText: "Decentralized. Unwavering.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "chosen_minion", action: "silence", params: {} },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_reserve_protocol",
    name: "Reserve Protocol",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    cost: 5,
    attack: 4,
    health: 5,
    text: "Pump: Restore your Hero to full HP.",
    flavorText: "Infinite liquidity. Almost.",
    keywordsJson: [{ id: "battlecry", display: "Pump" }],
    effectsJson: [
      { trigger: "on_play", target: "hero_friendly", action: "heal", params: { amount: 30 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  {
    id: "stable_the_fed",
    name: "The Fed",
    set: "genesis",
    type: "minion",
    faction: "stable",
    rarity: "rare",
    cost: 7,
    attack: 5,
    health: 8,
    text: "HODL. Pump: Reduce the cost of all cards in your hand by (1).",
    flavorText: "We will not hesitate to print.",
    keywordsJson: [
      { id: "taunt", display: "HODL" },
      { id: "battlecry", display: "Pump" },
    ],
    effectsJson: [
      { trigger: "passive", target: "self", action: "give_keyword", params: { keyword: "taunt" } },
      {
        trigger: "on_play",
        target: "hero_friendly",
        action: "modify_cost",
        params: { target: "all_cards_in_hand", amount: -1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 20,
    craftCost: 100,
  },
  // --- DEGEN CARDS ---
  {
    id: "degen_rug_pull",
    name: "Rug Pull",
    set: "genesis",
    type: "spell",
    faction: "degen",
    rarity: "epic",
    cost: 2,
    text: "Destroy a friendly minion. Draw 2 cards.",
    flavorText: '"It was always an exit strategy."',
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_play", target: "minion_friendly", action: "destroy", params: { target_selection: "chosen_minion" } },
      { trigger: "on_play", target: "hero_friendly", action: "draw_cards", params: { count: 2 } },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },
  // --- ETHEREUM CARDS ---
  {
    id: "ethereum_the_exchange",
    name: "The Exchange",
    set: "genesis",
    type: "location",
    faction: "ethereum",
    rarity: "epic",
    tribe: "Protocol",
    cost: 3,
    durability: 3,
    text: "Tap: Draw a card, then a random card in your hand costs (1) more.",
    keywordsJson: [],
    effectsJson: [
      { trigger: "on_tap", target: "hero_friendly", action: "draw_cards", params: { count: 1 } },
      {
        trigger: "on_tap",
        target: "random_card_in_hand_friendly",
        action: "modify_cost",
        params: { amount: 1 },
      },
    ],
    collectible: true,
    craftable: true,
    dustValue: 100,
    craftCost: 400,
  },
  // --- HERO CARDS ---
  {
    id: "card_hero_satoshi",
    name: "Satoshi",
    set: "genesis",
    type: "hero",
    faction: "bitcoin",
    rarity: "legendary",
    cost: 8,
    health: 30,
    armor: 5,
    text: "Hero Power — Mint: Add two 1/1 Tokens to your hand.",
    heroPowerJson: {
      id: "hp_satoshi_upgraded",
      name: "Mint (Upgraded)",
      cost: 2,
      description: "Add two 1/1 Tokens to your hand.",
      effect_type: "add_to_hand",
      effect_params: { card_id: "token_1_1", count: 2 },
    },
    keywordsJson: [],
    effectsJson: [{ trigger: "on_play", target: "hero_friendly", action: "give_armor", params: { amount: 5 } }],
    collectible: true,
    craftable: true,
    dustValue: 400,
    craftCost: 1600,
  },
];

// Starter deck card lists
const HODL_GANG_CARDS = [
  { id: "bitcoin_paper_hands", qty: 4 },
  { id: "bitcoin_baby_hodl", qty: 4 },
  { id: "bitcoin_block_defender", qty: 3 },
  { id: "bitcoin_mining_rig", qty: 3 },
  { id: "bitcoin_cold_wallet", qty: 2 },
  { id: "bitcoin_stack_sats", qty: 3 },
  { id: "bitcoin_hodl_the_line", qty: 3 },
  { id: "bitcoin_hardware_security", qty: 3 },
  { id: "bitcoin_maxi", qty: 2 },
  { id: "bitcoin_the_halving", qty: 3 },
];

const MEME_MACHINE_CARDS = [
  { id: "meme_moon_boy", qty: 4 },
  { id: "meme_doge_gang", qty: 4 },
  { id: "meme_pepe_deploy", qty: 3 },
  { id: "meme_hype_wave", qty: 3 },
  { id: "meme_diamond_frog", qty: 3 },
  { id: "meme_viral_tweet", qty: 3 },
  { id: "meme_to_the_moon", qty: 3 },
  { id: "meme_elon_shill", qty: 2 },
  { id: "meme_pump_it", qty: 3 },
  { id: "meme_100x_bet", qty: 2 },
];

const STABLECOIN_CONTROL_CARDS = [
  { id: "stable_risk_manager", qty: 4 },
  { id: "stable_yield_farmer", qty: 3 },
  { id: "stable_liquidation", qty: 3 },
  { id: "stable_flash_crash", qty: 3 },
  { id: "stable_collateral", qty: 3 },
  { id: "stable_peg_defence", qty: 3 },
  { id: "stable_stablecoin", qty: 3 },
  { id: "stable_dai_hard", qty: 3 },
  { id: "stable_reserve_protocol", qty: 3 },
  { id: "stable_the_fed", qty: 2 },
];

async function main() {
  console.log("Seeding heroes...");
  for (const hero of HEROES) {
    await prisma.hero.upsert({
      where: { id: hero.id },
      update: hero,
      create: hero,
    });
  }

  console.log("Seeding cards...");
  for (const card of CARDS) {
    await prisma.card.upsert({
      where: { id: card.id },
      update: card as Parameters<typeof prisma.card.upsert>[0]["create"],
      create: card as Parameters<typeof prisma.card.upsert>[0]["create"],
    });
  }

  console.log("Creating demo user with starter decks...");
  const demoUser = await prisma.user.upsert({
    where: { username: "demo" },
    update: {},
    create: {
      username: "demo",
      email: "demo@memetgc.gg",
      fragments: 500,
      isNewPlayer: false,
    },
  });

  // Grant all genesis cards to demo user
  for (const card of CARDS.filter((c) => c.collectible !== false)) {
    await prisma.collectionEntry.upsert({
      where: { userId_cardId: { userId: demoUser.id, cardId: card.id } },
      update: {},
      create: { userId: demoUser.id, cardId: card.id, quantity: 4 },
    });
  }

  // Create starter decks for demo user
  const starterDecks = [
    { name: "HODL Gang", heroId: "hero_satoshi", cards: HODL_GANG_CARDS },
    { name: "Meme Machine", heroId: "hero_elon", cards: MEME_MACHINE_CARDS },
    { name: "Stablecoin Control", heroId: "hero_circle_ceo", cards: STABLECOIN_CONTROL_CARDS },
  ];

  for (const starterDeck of starterDecks) {
    const existingDeck = await prisma.deck.findFirst({
      where: { userId: demoUser.id, name: starterDeck.name },
    });

    if (!existingDeck) {
      const deck = await prisma.deck.create({
        data: {
          userId: demoUser.id,
          name: starterDeck.name,
          heroId: starterDeck.heroId,
          isStarter: true,
          factionBonusActive: true,
        },
      });

      for (const { id, qty } of starterDeck.cards) {
        await prisma.deckCard.create({
          data: { deckId: deck.id, cardId: id, quantity: qty },
        });
      }
      console.log(`  Created starter deck: ${starterDeck.name}`);
    }
  }

  console.log("Seed complete!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
